
import platform

Import("bsp")

bspm = bsp.Clone()

if platform.uname()[0] != 'Windows':
	bspm.Append(LIBS= ['m'])

# we can only make this if we have MPI
bspm.Program('bspbench', ['bspbench.c', 'bspedupack.c'])
bspm.Program('bspfft', ['bspfft.c', 'bspfft_test.c', 'bspedupack.c'])
bspm.Program('bspinprod', ['bspinprod.c', 'bspedupack.c'])
bspm.Program('bsplu', ['bsplu.c', 'bsplu_test.c', 'bspedupack.c'])
bspm.Program('bspmv', ['bspmv.c', 'bspmv_test.c', 'bspedupack.c'])
