
Import("mpi", "sequential", "libsuffix")

files = [ 
	'bspx.c', 
	'bsp_www.c', 
	'bsp_abort.c', 
	'bsp_delivtable.c', 
	'bsp_exptable.c', 
	'bsp_memreg.c', 
	'bsp_reqtable.c',
	'bsp_global_drma.c',
	'bsp_time.c', 
	'bsp_mutex.c',
	# these are the files for the c++ part
	'bsp_cpp/bsp_commandline.cpp',
	'bsp_cpp/bsp_tbb.cpp',
	'bsp_cpp/bsp_context.cpp',
	'bsp_cpp/bsp_contextimpl.cpp',
	'bsp_cpp/bsp_contextimpl_memreg.cpp',
]

if sequential:
	files.append ('bsp_comm_seq.c')
else:
	files.append ('bsp_comm_mpi.c')

mpi.Library('#lib/bsponmpi'+libsuffix, files)

